### ISSUE TITLE
This is not an antidote, it's a detector

### ISSUE THREAD

**Issue by shemetz** [RichardAragon/NightshadeAntidote#4]
The name is misleading.  This tool doesn't seem to let you "unpoison" an image and put it into the dataset, it just marks those images.  So, it's not an antidote, it's a detector, a sensor, a poison taster.

Nightshade is still useful even when it isn't secret, by deterring inclusion in training datasets.

**Comment by RichardAragon** [comment]
I will give you the same response as the only other person who has realized that. If you can deduce that, then you can also deduce how to easily switch it into offense mode. I am not going to do that, personally. You can! I do not think an eye for an eye is good, I think balance in the force is good.

**Comment by Demon54000** [comment]
Why do you do an antidote? People are hating ai art, ai users, ect...
Why would you do an antidote do this solution? People want to keep their creation safe, why would you permit an antidote to steal their art? their work? 
I'm just so mad against you i hope you have good explanation :/

**Comment by Randy-H0** [comment]
> Why do you do an antidote? People are hating ai art, ai users, ect... Why would you do an antidote do this solution? People want to keep their creation safe, why would you permit an antidote to steal their art? their work? I'm just so mad against you i hope you have good explanation :/

AI is not stealing art. If you have looked at a few art pieces yourself and thought "Oh, I wanna make something in a similar style with a similar character", that is not stealing, that's drawing inspiration from the original work.

AI does the same. It learns how to draw alike and uses that to then be able to draw creative things that have not ever existed.

**Comment by Demon54000** [comment]
> > Why do you do an antidote? People are hating ai art, ai users, ect... Why would you do an antidote do this solution? People want to keep their creation safe, why would you permit an antidote to steal their art? their work? I'm just so mad against you i hope you have good explanation :/
> 
> AI is not stealing art. If you have looked at a few art pieces yourself and thought "Oh, I wanna make something in a similar style with a similar character", that is not stealing, that's drawing inspiration from the original work.
> 
> AI does the same. It learns how to draw alike and uses that to then be able to draw creative things that have not ever existed.

It is stealing. It's like making a copy, and selling it without giving a fuck about copyright or anything. Imagine learning how to draw from 8 to 18 and people can copy your work with just a screen or code :/
Like hell nah bro, whats next?

**Comment by shemetz** [comment]
This github issue isn't the place to argue in favor of or against the AI, it's just about the usage of the word "antidote" in the title!

**Comment by Demon54000** [comment]
If you arent happy its the same

**Comment by Randy-H0** [comment]
> This github issue isn't the place to argue in favor of or against the AI, it's just about the usage of the word "antidote" in the title!

Yeah, anyway did you get it to work with the unpoison thing, or is that not implemented?

**Comment by RenPT23** [comment]
> > Why do you do an antidote? People are hating ai art, ai users, ect... Why would you do an antidote do this solution? People want to keep their creation safe, why would you permit an antidote to steal their art? their work? I'm just so mad against you i hope you have good explanation :/
> 
> AI is not stealing art. If you have looked at a few art pieces yourself and thought "Oh, I wanna make something in a similar style with a similar character", that is not stealing, that's drawing inspiration from the original work.
> 
> AI does the same. It learns how to draw alike and uses that to then be able to draw creative things that have not ever existed.

are you some dumbass?
AI litrally goes up on the internet finding every single image into a database to then be used to create new images
